name: CI for containers

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        # Добавляем репозиторий LLVM для версии 18
        wget -qO- https://apt.llvm.org/llvm.sh | sudo bash -s 18
        sudo apt-get update
        
        # Устанавливаем пакеты
        sudo apt-get install -y \
          build-essential \
          cmake \
          valgrind \
          clang-format-18 \
          clang-tidy-18 \
          cppcheck \
          libgtest-dev
        
        # Настраиваем альтернативы для clang-tools
        sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-18 100
        sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-18 100

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --parallel

    - name: Run clang-format test
      run: |
        cd build
        cmake --build . --target clang-format-test
    
    - name: Run cppcheck
      run: |
        cd build
        cmake --build . --target cppcheck-test

    - name: Run clang-tidy
      run: |
        cd build
        cmake --build . --target clang-tidy-test

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel

    - name: Run valgrind tests
      run: |
        cd build
        cmake --build . --target valgrind-test
