name: CI for containers

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          cmake \
          clang-format \
          clang-tidy \
          cppcheck \
          libgtest-dev

    - name: Configure and build
      run: |
        mkdir -p build
        cd build
        cmake ..
        cmake --build . --parallel

    - name: Run clang-format test
      run: |
        cd build
        cmake --build . --target clang-format-test

    - name: Run clang-tidy
      run: |
        cd build
        cmake --build . --target clang-tidy-test

    - name: Run cppcheck
      run: |
        cd build
        cmake --build . --target cppcheck

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure --parallel

